Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RazorController.cs
using Microsoft.AspNetCore.Mvc;

namespace la_mia_pizzeria_static.Controllers
{
    public class RazorController : Controller
    {
        public IActionResult Snacks()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@*

un nome
una descrizione
una foto
un prezzo
Modifichiamo quindi la view Index.cshtml generata in automatico da .Net Core scrivendo l’html che serve a noi per mostrare l’elenco delle pizze (possiamo creare una tabella con bootstrap o una qualche grafica a nostro piacimento che mostri l’elenco delle pizze...proviamo un po’ di creatività se vogliamo!)
Buon lavoro!! :faccia_leggermente_sorridente:*@

@{
    Layout = "_Layout";

    Random rand = new Random();

    string[] name = { "margherita", "parigniana", "fiori di zucca", "capricciosa", "napoletana", "funghi porcini" };
}


<h1 style="text-align:center">le mie pizze</h1>

<div class="container-fluid row p-2 border-2 " style="margin-top:20px; background-color:antiquewhite">
    @for (int i = 0; i < 10; i++)
    {
            <div class="card m-2" style="width: 18rem; background-color:bisque" >
                <img src="https://picsum.photos/200/300?random=\@i" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title"> @name[rand.Next(0,5)] </h5>
                    <p class="card-text">lorem ipsum, e testo vario </p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">prezzo @rand.Next(1, 10) € </li>
                        @*    <li class="list-group-item">A second item</li>
                                <li class="list-group-item">A third item</li>*@
                </ul>
                            @*  <div class="card-body">
                        <a href="#" class="card-link">Card link</a>
                        <a href="#" class="card-link">Another link</a>
                        </div>*@
            </div>
    }
</div>

Views/Razor/Snacks.cshtml
@{
    Layout = "_mylayoutSnacks";
}

<h1> esercitazione a snack </h1>

<div class="container-fluid"> 
    <div class="container-lg m-2 border border-primary" style=" background-color:aliceblue">
        <h2 style="color:red" > snack 1 </h2>
        <p> 1. Dichiarare una variabile valorizzandola con il nostro nome.
Dichiarare un'altra variabile valorizzandola con il nostro cognome.
Stampare il nostro nome e cognome all'interno di un tag h2. </p>

        <div style="background-color:aqua">
            @{
                string name = "anthony";
                string surname = "anthony";
            }

            <h2> @name @surname  </h2>

        </div>
    </div>

    <div class="container-lg m-2 border border-primary" style=" background-color:aliceblue">
        <h2 style="color:red" > snack 2 </h2>
        <p> 2. Creare una funzione che stampa la somma dei numeri che vanno da 1 a n (con n passato come parametro - n incluso)
              Stampare dentro uno span il risultato. </p>

        <div style="background-color:aqua">
            @{
                Random rand = new Random();
                int n = rand.Next(1, 10);
                int result = 0;

                for (int i = 1; i < n; i++)
                {
                    result += i;
                }

            }
            <p> risultato è @result </p>

        </div>
    </div>

    <div class="container-lg m-2 border border-primary" style=" background-color:aliceblue">
        <h2 style="color:red" > snack 3 </h2>
        <p> 3. Contare quante volte la lettera a è presente nalla frase "nel mezzo del cammin di nostra vita" e stampare questo valore in pagina </p>

        <div style="background-color:aqua">
            @{
                string text = "nel mezzo del cammin di nostra vita";
                int ann = 0;
                foreach (var item in text)
                {
                    if(Convert.ToString(item) == "a"){
                        ann += 1;
                    }
                }
            }
            <p> la a ricorre @ann volte </p>


        </div>
    </div>
    
    <div class="container-lg m-2 border border-primary" style=" background-color:aliceblue">
        <h2 style="color:red" > snack 4 </h2>
        <p>4. Creare una List int di 20 numeri interi (generati random da 1 a 90, 1 e 90 inclusi) e mostrare in pagina solo i numeri compresi tra 20 e 70</p>

        <div style="background-color:aqua">
            @{
                List<int> numbers = new List<int>();
                for (int i = 0; i < 20; i++)
                {
                    int nRand = rand.Next(1,90);
                    numbers.Add(nRand);

                    if (nRand > 20 && nRand < 70){
                                <span> @nRand </span>
                    }
                }
            }


        </div>
    </div>

    <div class="container-lg m-2 border border-primary" style=" background-color:aliceblue">
        <h2 style="color:red" > snack 5 </h2>
        <p> 5. Stampare in pagina la data e l'ora attuale (usando la classe DateTime) con il formato anno-mese-giorno ore:minuti:secondi </p>

        <div style="background-color:aqua">
            @{
                DateTime date =  DateTime.Now;
            }
            <p> @date.ToString("d"); </p>

        </div>
    </div>

        <div class="container-lg m-2 border border-primary" style=" background-color:aliceblue">
        <h2 style="color:red" > snack 6 </h2>
        <p> 6. Partendo dalla data di oggi (usando la classe DateTime) stampare in pagina <br/>   
            a. la data di 7 giorni fa<br/> 
            b. che giorno della settimana è oggi (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)<br/> 
            c. che giorno della settimana sarà nello stesso giorno e mese di oggi ma tra un anno (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...) </p>

        <div style="background-color:aqua">
            <p> 7 giorni fa era  @date.AddDays(-7)  </p>
            <p> oggi è @date.DayOfWeek.ToString() </p>
            <p> tra un anno sarà @date.AddYears(1).DayOfWeek.ToString() </p>

        </div>
    </div>

    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">la_mia_pizzeria_static</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Razor" asp-action="Snacks">Snacks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_mylayoutSnacks.cshtml
<html>
<head>
<title>Il mio primo layout</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>

<main>
        @RenderBody()
</main>

</body>
</html>